// Observed Milky Way stars; source notes are in docs/observed-stars-sources.md.
// Scene positions, sizes, colors and surface motion are composed for exploration.
// A confirmed object does not imply a photographically reconstructed surface.
export const observedStarDefinitions = [
  {
    id: 'polaris', cn: '北极星 A', en: 'POLARIS Aa', index: 'α UMI Aa',
    type: '银河系 / 造父变星',
    position: [-16000, 1700, -11800], r: 23, surfaceStyle: 'gold-star', color: 0xffe7b6,
    diameter: '造父变星', stat1: '恒星类型',
    stat2: '所属星座', value2: '小熊座',
    desc: '位于北天极附近，是小熊座中熟悉的指北亮星。北极星其实属于三星系统；本次探访的是肉眼所见的主要成员 Polaris Aa，一颗会随脉动改变亮度的造父变星。',
    sourceUrl: 'https://www.eso.org/public/blog/probing-polaris/',
    sourceLabel: 'ESO · 北极星与造父变星',
    appearance: '柔和金白星面、浅暖颗粒与明亮外晕',
  },
  {
    id: 'altair', cn: '牛郎星', en: 'ALTAIR', index: 'α AQL',
    type: '银河系 / 蓝白主序星',
    position: [-7300, 250, -8600], r: 12, surfaceStyle: 'blue-star', color: 0xd0e7ff,
    diameter: '约 17', stat1: '距地球', unit1: '光年',
    stat2: '所属星座', value2: '天鹰座',
    desc: '与织女星、天津四组成夏季大三角，是天鹰座的明亮恒星。它自转很快，真实星体的赤道因此鼓起；天文学家通过干涉成像观测到了它的形状与星面亮度差异。',
    sourceUrl: 'https://science.nasa.gov/solar-system/skywatching/night-sky-network/summer-triangle-corner-altair/',
    sourceLabel: 'NASA · 牛郎星与夏季大三角',
    appearance: '清透蓝白光球与冰蓝外缘',
  },
  {
    id: 'arcturus', cn: '大角星', en: 'ARCTURUS', index: 'α BOO',
    type: '银河系 / 红巨星',
    position: [-14200, 820, 11800], r: 21, surfaceStyle: 'gold-star', color: 0xffb877,
    diameter: '约 37', stat1: '距地球', unit1: '光年',
    stat2: '所属星座', value2: '牧夫座',
    desc: '沿北斗斗柄的弧线延伸，可以找到这颗温暖的橙色亮星。大角星已经进入红巨星阶段，膨胀的外层比太阳表面更冷；在画面中可近看它柔和的橙金光球。',
    sourceUrl: 'https://science.nasa.gov/universe/stars/types/',
    sourceLabel: 'NASA · 恒星类型与大角星',
    appearance: '橙金色巨星光球与舒缓对流斑纹',
  },
  {
    id: 'aldebaran', cn: '毕宿五', en: 'ALDEBARAN', index: 'α TAU',
    type: '银河系 / 红巨星',
    position: [-28800, -450, 9700], r: 23, surfaceStyle: 'red-star', color: 0xffa373,
    diameter: '约 65', stat1: '距地球', unit1: '光年',
    stat2: '所属星座', value2: '金牛座',
    desc: '金牛座眼睛位置的橙红色巨星。它看上去落在 V 字形的毕星团中，实际上比星团更靠近地球；这颗前景恒星与远处星团恰好位于相近的视线方向。',
    sourceUrl: 'https://nightsky.jpl.nasa.gov/documents/787/ObserverCardsRed1.pdf',
    sourceLabel: 'NASA / JPL · 红巨星观测卡',
    appearance: '深橙红光球、暖色颗粒与柔软星晕',
  },
  {
    id: 'deneb', cn: '天津四', en: 'DENEB', index: 'α CYG',
    type: '银河系 / 蓝白超巨星',
    position: [-27200, 1050, -11100], r: 29, surfaceStyle: 'blue-star', color: 0xaecfff,
    diameter: '蓝白超巨星', stat1: '恒星类型',
    stat2: '所属星座', value2: '天鹅座',
    desc: '标记着天鹅座的尾部，也是夏季大三角的一角。天津四是一颗明亮的蓝白超巨星；沿它所在的天鹅座望去，可以看到银河穿过密集星野的方向。',
    sourceUrl: 'https://www.jpl.nasa.gov/videos/whats-up-october-2021/',
    sourceLabel: 'NASA / JPL · 天津四与织女星',
    appearance: '宽阔蓝白星面与冷色辉光',
  },
  {
    id: 'canopus', cn: '南船二', en: 'CANOPUS', index: 'α CAR',
    type: '银河系 / 航天导航恒星',
    position: [-31900, -950, -4600], r: 26, surfaceStyle: 'gold-star', color: 0xffefcf,
    diameter: '船底座', stat1: '所属星座',
    stat2: '航天用途', value2: '姿态参考',
    desc: '又称老人星，是南方天空中醒目的亮星。水手 7 号曾使用星敏感器锁定南船二，并与太阳一起作为飞行姿态参考，让这颗遥远恒星参与了人类的火星探索。',
    sourceUrl: 'https://www.jpl.nasa.gov/news/mariner-7-to-complete-star-acquisition-sequence/',
    sourceLabel: 'NASA / JPL · 水手 7 号与南船二',
    appearance: '明亮暖白星面与淡金细晕',
  },
  {
    id: 'antares', cn: '心宿二 A', en: 'ANTARES A', index: 'α SCO A',
    type: '银河系 / 红超巨星',
    position: [-21100, 350, -15500], r: 30, surfaceStyle: 'red-star', color: 0xff8156,
    diameter: '红超巨星', stat1: '恒星类型',
    stat2: '所属星座', value2: '天蝎座',
    desc: '位于天蝎座心脏位置，闪耀着鲜明的橙红色光芒。这里展示主星心宿二 A；ESO 的甚大望远镜干涉仪曾解析它的星面与大气运动，揭示庞大外层中复杂的气体流动。',
    sourceUrl: 'https://www.eso.org/public/news/eso1726/',
    sourceLabel: 'ESO · 心宿二星面与大气观测',
    appearance: '宽大橙红光球与翻涌的深浅对流斑',
  },
  {
    id: 'barnard-star', cn: '巴纳德星', en: 'BARNARD’S STAR', index: 'GJ 699',
    type: '银河系 / 红矮星',
    position: [-6100, -120, 6100], r: 5.5, surfaceStyle: 'red-star', color: 0xff7654,
    diameter: '约 6', stat1: '距地球', unit1: '光年',
    stat2: '所属星座', value2: '蛇夫座',
    desc: '太阳附近的一颗暗淡红矮星，位于蛇夫座方向，需要借助望远镜观察。它与太阳的距离只有约 6 光年，天文学家长期测量它的微小运动，寻找围绕它运行的行星。',
    sourceUrl: 'https://www.eso.org/public/news/eso2414/',
    sourceLabel: 'ESO · 巴纳德星观测',
    appearance: '小巧的暗红星面与柔和橙色外晕',
  },
].map((definition) => ({
  kind: 'star', modelStatus: 'confirmed', parentId: 'galaxy', parentGalaxy: 'galaxy',
  unit1: '', unit2: '',
  ...definition,
}));
